export const iconMap = {
  "clear sky": "clear-day",
  "few clouds": "partly-cloudy-day",
  "scattered clouds": "partly-cloudy-day",
  "broken clouds": "cloudy",
  "overcast clouds": "overcast-day",

  "light rain": "rain",
  "moderate rain": "rain",
  "heavy intensity rain": "extreme-rain",            
  "very heavy rain": "extreme-rain",
  "extreme rain": "extreme-rain",
  "freezing rain": "sleet",                          
  "light intensity shower rain": "drizzle",
  "shower rain": "drizzle",
  "heavy intensity shower rain": "extreme-rain",       
  "ragged shower rain": "drizzle",                   

  "light snow": "snow",                              
  "snow": "snow",
  "heavy snow": "extreme-snow",                              
  "sleet": "sleet",
  "light shower sleet": "sleet",                     
  "shower sleet": "sleet",
  "light rain and snow": "sleet",                    
  "rain and snow": "sleet",                          
  "light shower snow": "snow",                       
  "shower snow": "snow",
  "heavy shower snow": "extreme-snow",                       

  "mist": "mist",
  "smoke": "smoke",
  "haze": "haze",
  "sand/dust whirls": "dust",
  "fog": "fog",
  "sand": "dust",
  "dust": "dust",
  "volcanic ash": "fog",                              
  "squalls": "wind",
  "tornado": "tornado",

  "thunderstorm with light rain": "thunderstorms-rain",
  "thunderstorm with rain": "thunderstorms-rain",
  "thunderstorm with heavy rain": "thunderstorms-extreme-rain",
  "light thunderstorm": "thunderstorms",
  "thunderstorm": "thunderstorms",
  "heavy thunderstorm": "thunderstorms-extreme",
  "ragged thunderstorm": "thunderstorms-extreme",
  "thunderstorm with light drizzle": "thunderstorms",      
  "thunderstorm with drizzle": "thunderstorms",            
  "thunderstorm with heavy drizzle": "thunderstorms-extreme",   

  // Remaining descriptions
  "overcast": "overcast-day",
  "clear": "clear-day",
  "clouds": "cloudy",
  "drizzle": "drizzle",
  "rain": "rain",
  "snow shower": "snow",                              
  "shower snow": "snow",
  "heavy snow shower": "extreme-snow",                  
  "light thunderstorm rain": "thunderstorms-rain",    
  "thunderstorm rain": "thunderstorms-rain",          
  "heavy thunderstorm rain": "thunderstorms-extreme", 
  "smoke haze": "smoke",                               
  "dust storm": "dust",                                
  "fog mist": "fog",                                   
  "squall wind": "wind",
  "tornado funnel": "tornado"
};

